[tool.poetry]
name = "gemini"
version = "0.1.0"
description = ""
authors = ["abhinav-raj-dev <abhinavraj157@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pillow = "^11.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
